USE SistemaRPG

--TABELAS
CREATE TABLE Cadastro
(
	COD_LOGIN INT PRIMARY KEY IDENTITY NOT NULL,
	NOME VARCHAR(70) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR (20) NOT NULL,
	PERFIL VARCHAR(15) NOT NULL,
	ATIVO INT NOT NULL
)

CREATE TABLE Personagem 
(
	COD_PER INT PRIMARY KEY IDENTITY NOT NULL,
	COD_LOGIN INT NOT NULL,
	NOME_PER VARCHAR(50) NOT NULL,
	IMG_PER INT NOT NULL,
	RACA_PER VARCHAR(20) NOT NULL,
	FORCA_PER INT NOT NULL,
	TIPO_PER VARCHAR(20) NOT NULL,
	NIVEL_PER INT NULL,
	HAB_PER INT NULL,
	RES_PER  INT NULL,
	ARM_PER INT NULL,
	PV_PER INT NULL,
	PDF_PER INT NULL
)

CREATE TABLE Caracteristica
(
	COD_CARAC INT PRIMARY KEY IDENTITY NOT NULL,
	NOME_CARAC VARCHAR(50) NOT NULL,
	MOD_CARAC INT NULL,
	TIPO_CARAC VARCHAR(20) NULL
)

CREATE TABLE Aventura
(
	COD_AVENTURA INT PRIMARY KEY IDENTITY NOT NULL,
	COD_LOGIN INT NULL,
	AVENTURA VARCHAR(100) NOT NULL,
	SENHA VARCHAR(20) NOT NULL
)

CREATE TABLE Partida
(
	COD_PARTIDA INT PRIMARY KEY IDENTITY NOT NULL,
	COD_AVENTURA INT NULL,
	DESCRICAO VARCHAR(500) NOT NULL,
	SENHA VARCHAR(20) NOT NULL,
)

CREATE TABLE Resultados
(
	COD_RESULTADOS INT PRIMARY KEY IDENTITY NOT NULL,
	DATA DATETIME NOT NULL,
	RESULTADO INT NOT NULL
)

-- TABELAS DE RELACIONAMENTO
CREATE TABLE Personagem_Caracteristica
(
	COD_PER INT NOT NULL,
	COD_CARAC INT NOT NULL
)

CREATE TABLE Partida_Resultados
(
	COD_PARTIDA INT NOT NULL,
	COD_RESULTADOS INT NOT NULL
)

-- CHAVES ESTRANGEIRAS
ALTER TABLE Personagem
ADD CONSTRAINT Fk_Personagem_Cadastro
FOREIGN KEY (COD_LOGIN)
REFERENCES Cadastro (COD_LOGIN)

ALTER TABLE Personagem
ADD CONSTRAINT Fk_Personagem_Caracteristica
FOREIGN KEY (COD_PER)
REFERENCES Personagem_Caracteristica (COD_PER)

ALTER TABLE Caracteristica
ADD CONSTRAINT  Fk_Caracteristica_Personagem
FOREIGN KEY (COD_CARAC)
REFERENCES Personagem_Caracteristica (COD_CARAC)

ALTER TABLE Aventura
ADD CONSTRAINT Fk_Aventura_Jogador
FOREIGN KEY (COD_LOGIN)
REFERENCES Cadastro (COD_LOGIN)

ALTER TABLE Partida
ADD CONSTRAINT Fk_Parida_Aventura
FOREIGN KEY (COD_AVENTURA)
REFERENCES Aventura (COD_AVENTURA)

ALTER TABLE Partida
ADD CONSTRAINT Fk_Partida
FOREIGN KEY (COD_PARTIDA)
REFERENCES Partida_Resultados (COD_PARTIDA)

ALTER TABLE Resultados
ADD CONSTRAINT Fk_Resultado
FOREIGN KEY (COD_RESULTADOS)
REFERENCES Partida_Resultados (COD_RESULTADOS)

-- INSERT/SELECT
INSERT INTO Cadastro (NOME, EMAIL, SENHA, PERFIL, ATIVO) VALUES ('Mario Vieira Junior', 'marioviera_mvj@hotmail.com', '123', 'Administrador', 1)
INSERT INTO Cadastro (NOME, EMAIL, SENHA, PERFIL, ATIVO) VALUES ('Bruno Duran', 'bduran@gmail.com', '123', 'Administrador', 1)
INSERT INTO Cadastro (NOME, EMAIL, SENHA, PERFIL, ATIVO) VALUES ('Mestre', 'mestre@hotmail.com', '123', 'Administrador', 1)
INSERT INTO Cadastro (NOME, EMAIL, SENHA, PERFIL, ATIVO) VALUES ('Jogador', 'jogador@gmail.com', '123', 'Usuario', 1)

SELECT * FROM Cadastro

INSERT INTO Personagem (NOME_PER, IMG_PER, RACA_PER, FORCA_PER, TIPO_PER, NIVEL_PER, HAB_PER, RES_PER, ARM_PER, PV_PER, PDF_PER) 
				VALUES ('Jogador Mortal', 2, 'Elfo', 2, 'Nulo', 1, 1, 1, 1, 2, 2)
INSERT INTO Personagem (NOME_PER, IMG_PER, RACA_PER, FORCA_PER, TIPO_PER, NIVEL_PER) 
				VALUES ('Jogador Mortal 2', 2, 'Elfo', 2, 'Nulo 2', 1)
INSERT INTO Personagem (NOME_PER, IMG_PER, RACA_PER, FORCA_PER, TIPO_PER, NIVEL_PER, HAB_PER, RES_PER, ARM_PER, PV_PER, PDF_PER) 
				VALUES ('Imortal', 1, 'Humano', 1, 'Cidadão', 1, 0, 0, 0, 1, 1)
INSERT INTO Personagem (NOME_PER, IMG_PER, RACA_PER, FORCA_PER, TIPO_PER) 
				VALUES ('Mortal', 1, 'Humano', 1, 'Soldado')

SELECT * FROM Personagem

INSERT INTO Caracteristica (NOME_CARAC, MOD_CARAC, TIPO_CARAC) VALUES ('Ataque', 2, 'Vantagem')
INSERT INTO Caracteristica (NOME_CARAC, MOD_CARAC, TIPO_CARAC) VALUES ('Fuga', 1, 'Desvantagem')

SELECT * FROM Caracteristica

INSERT INTO Aventura (AVENTURA, SENHA) VALUES ('Duelo de Mestres', '007')
INSERT INTO Aventura (COD_LOGIN, AVENTURA, SENHA) VALUES (1, 'Duelo de SHIVA', 'shiva')
INSERT INTO Aventura (COD_LOGIN, AVENTURA, SENHA) VALUES (2, 'Duelo de SHIVA', 'shiva')
INSERT INTO Aventura (COD_LOGIN, AVENTURA, SENHA) VALUES (3, 'Duelo de SHIVA', 'shiva')
INSERT INTO Aventura (COD_LOGIN, AVENTURA, SENHA) VALUES (4, 'Duelo de SHIVA', 'shiva')

SELECT * FROM Aventura
SELECT * FROM Aventura a, Cadastro c WHERE a.COD_LOGIN = c.COD_LOGIN

INSERT INTO Partida (COD_AVENTURA, DESCRICAO, SENHA) VALUES (1, 'Todos morrem se não seguir as ordens do Mestre', '123')
INSERT INTO Partida (COD_AVENTURA, DESCRICAO, SENHA) VALUES (2, 'Cuidado com o monstro de quatro braços', '123')

SELECT * FROM Partida
SELECT * FROM Aventura a, Cadastro c, Partida p WHERE a.COD_LOGIN = c.COD_LOGIN AND a.COD_AVENTURA = p.COD_AVENTURA

INSERT INTO Resultados (DATA, RESULTADO) VALUES ('2014-05-03 02:22:20.521', '25')
INSERT INTO Resultados (DATA, RESULTADO) VALUES ('2014-05-03 02:35:29.123', '100')

SELECT * FROM Resultados
